//! Semantic token encoding for LSP.
//!
//! Walks the tree-sitter CST and produces delta-encoded semantic tokens
//! for syntax highlighting.

use tower_lsp::lsp_types::{SemanticToken, SemanticTokenType, SemanticTokensLegend};
use std::sync::LazyLock;
use tree_sitter::{Node, Tree};

// Token type indices (must match LEGEND order)
const TT_KEYWORD: u32 = 0;
const TT_TYPE: u32 = 1;
const TT_VARIABLE: u32 = 2;
const TT_FUNCTION: u32 = 3;
const TT_PARAMETER: u32 = 4;
const TT_NUMBER: u32 = 5;
const TT_STRING: u32 = 6;
const TT_COMMENT: u32 = 7;
#[allow(dead_code)]
const TT_OPERATOR: u32 = 8;
const TT_ENUM_MEMBER: u32 = 9;

pub static LEGEND: LazyLock<SemanticTokensLegend> = LazyLock::new(|| SemanticTokensLegend {
    token_types: vec![
        SemanticTokenType::KEYWORD,       // 0
        SemanticTokenType::TYPE,          // 1
        SemanticTokenType::VARIABLE,      // 2
        SemanticTokenType::FUNCTION,      // 3
        SemanticTokenType::PARAMETER,     // 4
        SemanticTokenType::NUMBER,        // 5
        SemanticTokenType::STRING,        // 6
        SemanticTokenType::COMMENT,       // 7
        SemanticTokenType::OPERATOR,      // 8
        SemanticTokenType::ENUM_MEMBER,   // 9
    ],
    token_modifiers: vec![],
});

pub struct TokenBuilder<'a> {
    source: &'a str,
    tokens: Vec<RawToken>,
}

struct RawToken {
    line: u32,
    col: u32,
    length: u32,
    token_type: u32,
}

impl<'a> TokenBuilder<'a> {
    pub fn new(source: &'a str) -> Self {
        Self {
            source,
            tokens: Vec::new(),
        }
    }

    pub fn build_from_tree(&mut self, tree: &Tree, source: &[u8]) {
        self.walk_node(tree.root_node(), source);
    }

    fn walk_node(&mut self, node: Node, source: &[u8]) {
        let kind = node.kind();

        // Handle leaf nodes that we want to tokenize
        match kind {
            // Keywords — these are anonymous nodes generated by the kw() helper
            // They appear as the raw keyword text
            "PROGRAM" | "END_PROGRAM" | "FUNCTION" | "END_FUNCTION"
            | "FUNCTION_BLOCK" | "END_FUNCTION_BLOCK" | "TYPE" | "END_TYPE"
            | "STRUCT" | "END_STRUCT" | "VAR" | "VAR_INPUT" | "VAR_OUTPUT"
            | "VAR_IN_OUT" | "VAR_GLOBAL" | "VAR_EXTERNAL" | "VAR_TEMP"
            | "END_VAR" | "IF" | "THEN" | "ELSIF" | "ELSE" | "END_IF"
            | "CASE" | "OF" | "END_CASE" | "FOR" | "TO" | "BY" | "DO"
            | "END_FOR" | "WHILE" | "END_WHILE" | "REPEAT" | "UNTIL"
            | "END_REPEAT" | "RETURN" | "EXIT" | "ARRAY" | "RETAIN"
            | "PERSISTENT" | "CONSTANT" | "AND" | "OR" | "XOR" | "NOT"
            | "MOD" | "TRUE" | "FALSE" => {
                self.push_token(&node, TT_KEYWORD);
            }
            // Type keywords
            "BOOL" | "SINT" | "INT" | "DINT" | "LINT"
            | "USINT" | "UINT" | "UDINT" | "ULINT"
            | "REAL" | "LREAL" | "BYTE" | "WORD" | "DWORD" | "LWORD"
            | "TIME" | "LTIME" | "DATE" | "LDATE"
            | "TIME_OF_DAY" | "TOD" | "LTOD"
            | "DATE_AND_TIME" | "DT" | "LDT"
            | "STRING" | "WSTRING" => {
                self.push_token(&node, TT_TYPE);
            }
            _ => {}
        }

        // Handle named nodes
        match kind {
            "line_comment" | "block_comment" => {
                self.push_token(&node, TT_COMMENT);
                return; // don't recurse into comments
            }
            "integer_literal" | "real_literal" | "time_literal"
            | "date_literal" | "tod_literal" | "dt_literal" => {
                self.push_token(&node, TT_NUMBER);
                return;
            }
            "string_literal" => {
                self.push_token(&node, TT_STRING);
                return;
            }
            "boolean_literal" => {
                self.push_token(&node, TT_KEYWORD);
                return;
            }
            _ => {}
        }

        // Recurse into children
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            // Check for contextual token types based on parent
            let child_kind = child.kind();
            if child_kind == "identifier" {
                let token_type = self.classify_identifier(&child, &node, source);
                self.push_token(&child, token_type);
            } else {
                self.walk_node(child, source);
            }
        }
    }

    fn classify_identifier(&self, node: &Node, parent: &Node, _source: &[u8]) -> u32 {
        let parent_kind = parent.kind();

        // Check the field name if available
        match parent_kind {
            "program_declaration" | "function_declaration" | "function_block_declaration" => {
                if parent.child_by_field_name("name").map(|n| n.id()) == Some(node.id()) {
                    return TT_FUNCTION;
                }
            }
            "type_definition" => {
                if parent.child_by_field_name("name").map(|n| n.id()) == Some(node.id()) {
                    return TT_TYPE;
                }
            }
            "variable_declaration" => {
                return TT_VARIABLE;
            }
            "struct_field" => {
                if parent.child_by_field_name("name").map(|n| n.id()) == Some(node.id()) {
                    return TT_VARIABLE;
                }
            }
            "named_argument" => {
                if parent.child_by_field_name("name").map(|n| n.id()) == Some(node.id()) {
                    return TT_PARAMETER;
                }
            }
            "enum_value" => {
                return TT_ENUM_MEMBER;
            }
            "function_call" | "qualified_name" => {
                // First identifier in a function_call's name is the function name
                return TT_FUNCTION;
            }
            "for_statement" => {
                if parent.child_by_field_name("variable").map(|n| n.id()) == Some(node.id()) {
                    return TT_VARIABLE;
                }
            }
            "variable_access" => {
                return TT_VARIABLE;
            }
            "assignment_statement" => {
                return TT_VARIABLE;
            }
            _ => {}
        }

        TT_VARIABLE
    }

    fn push_token(&mut self, node: &Node, token_type: u32) {
        let start = node.start_position();
        let end = node.end_position();

        // For multi-line tokens (like block comments), emit one token per line
        if start.row == end.row {
            self.tokens.push(RawToken {
                line: start.row as u32,
                col: start.column as u32,
                length: (end.column - start.column) as u32,
                token_type,
            });
        } else {
            // First line
            let first_line_end = self.source.lines().nth(start.row).map(|l| l.len()).unwrap_or(0);
            self.tokens.push(RawToken {
                line: start.row as u32,
                col: start.column as u32,
                length: (first_line_end - start.column) as u32,
                token_type,
            });
            // Middle lines
            for row in (start.row + 1)..end.row {
                let line_len = self.source.lines().nth(row).map(|l| l.len()).unwrap_or(0);
                self.tokens.push(RawToken {
                    line: row as u32,
                    col: 0,
                    length: line_len as u32,
                    token_type,
                });
            }
            // Last line
            if end.column > 0 {
                self.tokens.push(RawToken {
                    line: end.row as u32,
                    col: 0,
                    length: end.column as u32,
                    token_type,
                });
            }
        }
    }

    /// Convert raw tokens to delta-encoded LSP semantic tokens.
    pub fn finish(mut self) -> Vec<SemanticToken> {
        // Sort by position
        self.tokens.sort_by_key(|t| (t.line, t.col));

        let mut result = Vec::with_capacity(self.tokens.len());
        let mut prev_line = 0u32;
        let mut prev_col = 0u32;

        for tok in &self.tokens {
            if tok.length == 0 {
                continue;
            }
            let delta_line = tok.line - prev_line;
            let delta_start = if delta_line == 0 {
                tok.col - prev_col
            } else {
                tok.col
            };

            result.push(SemanticToken {
                delta_line,
                delta_start,
                length: tok.length,
                token_type: tok.token_type,
                token_modifiers_bitset: 0,
            });

            prev_line = tok.line;
            prev_col = tok.col;
        }

        result
    }
}
